package Primero;
// Generated 18 ene. 2021 10:01:31 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

	private int numalumno;
	private String nombre;
	private Byte edad;
	private Set moduloses = new HashSet(0);

	public Alumnos() {
	}

	public Alumnos(int numalumno) {
		this.numalumno = numalumno;
	}

	public Alumnos(int numalumno, String nombre, Byte edad, Set moduloses) {
		this.numalumno = numalumno;
		this.nombre = nombre;
		this.edad = edad;
		this.moduloses = moduloses;
	}

	public int getNumalumno() {
		return this.numalumno;
	}

	public void setNumalumno(int numalumno) {
		this.numalumno = numalumno;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Byte getEdad() {
		return this.edad;
	}

	public void setEdad(Byte edad) {
		this.edad = edad;
	}

	public Set getModuloses() {
		return this.moduloses;
	}

	public void setModuloses(Set moduloses) {
		this.moduloses = moduloses;
	}

}
