package Primero;
// Generated 18 ene. 2021 10:01:31 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Modulos generated by hbm2java
 */
public class Modulos implements java.io.Serializable {

	private String modulo;
	private Set alumnoses = new HashSet(0);

	public Modulos() {
	}

	public Modulos(String modulo) {
		this.modulo = modulo;
	}

	public Modulos(String modulo, Set alumnoses) {
		this.modulo = modulo;
		this.alumnoses = alumnoses;
	}

	public String getModulo() {
		return this.modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	public Set getAlumnoses() {
		return this.alumnoses;
	}

	public void setAlumnoses(Set alumnoses) {
		this.alumnoses = alumnoses;
	}

}
