package Primero;
// Generated 3 feb. 2021 14:08:07 by Hibernate Tools 5.4.27.Final

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private int dni;
	private String nombreRazonSocial;
	private String direccion;
	private String telfonoFax;
	private String email;

	public Clientes() {
	}

	public Clientes(int dni, String nombreRazonSocial) {
		this.dni = dni;
		this.nombreRazonSocial = nombreRazonSocial;
	}

	public Clientes(int dni, String nombreRazonSocial, String direccion, String telfonoFax, String email) {
		this.dni = dni;
		this.nombreRazonSocial = nombreRazonSocial;
		this.direccion = direccion;
		this.telfonoFax = telfonoFax;
		this.email = email;
	}

	public int getDni() {
		return this.dni;
	}

	public void setDni(int dni) {
		this.dni = dni;
	}

	public String getNombreRazonSocial() {
		return this.nombreRazonSocial;
	}

	public void setNombreRazonSocial(String nombreRazonSocial) {
		this.nombreRazonSocial = nombreRazonSocial;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelfonoFax() {
		return this.telfonoFax;
	}

	public void setTelfonoFax(String telfonoFax) {
		this.telfonoFax = telfonoFax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
