package Primero;
// Generated 25 ene. 2021 13:56:14 by Hibernate Tools 5.4.21.Final

import java.util.Date;

/**
 * FilmActor generated by hbm2java
 */
public class FilmActor implements java.io.Serializable {

	private FilmActorId id;
	private Actor actor;
	private Date lastUpdate;

	public FilmActor() {
	}

	public FilmActor(FilmActorId id, Actor actor, Date lastUpdate) {
		this.id = id;
		this.actor = actor;
		this.lastUpdate = lastUpdate;
	}

	public FilmActorId getId() {
		return this.id;
	}

	public void setId(FilmActorId id) {
		this.id = id;
	}

	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
