package Primero;
// Generated 18 ene. 2021 9:58:01 by Hibernate Tools 5.4.21.Final

import java.math.BigDecimal;

/**
 * DetallepresupuestosId generated by hbm2java
 */
public class DetallepresupuestosId implements java.io.Serializable {

	private Integer numPresupuesto;
	private Integer codProducto;
	private BigDecimal precioUnidad;
	private BigDecimal cantidad;

	public DetallepresupuestosId() {
	}

	public DetallepresupuestosId(Integer numPresupuesto, Integer codProducto, BigDecimal precioUnidad,
			BigDecimal cantidad) {
		this.numPresupuesto = numPresupuesto;
		this.codProducto = codProducto;
		this.precioUnidad = precioUnidad;
		this.cantidad = cantidad;
	}

	public Integer getNumPresupuesto() {
		return this.numPresupuesto;
	}

	public void setNumPresupuesto(Integer numPresupuesto) {
		this.numPresupuesto = numPresupuesto;
	}

	public Integer getCodProducto() {
		return this.codProducto;
	}

	public void setCodProducto(Integer codProducto) {
		this.codProducto = codProducto;
	}

	public BigDecimal getPrecioUnidad() {
		return this.precioUnidad;
	}

	public void setPrecioUnidad(BigDecimal precioUnidad) {
		this.precioUnidad = precioUnidad;
	}

	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetallepresupuestosId))
			return false;
		DetallepresupuestosId castOther = (DetallepresupuestosId) other;

		return ((this.getNumPresupuesto() == castOther.getNumPresupuesto())
				|| (this.getNumPresupuesto() != null && castOther.getNumPresupuesto() != null
						&& this.getNumPresupuesto().equals(castOther.getNumPresupuesto())))
				&& ((this.getCodProducto() == castOther.getCodProducto())
						|| (this.getCodProducto() != null && castOther.getCodProducto() != null
								&& this.getCodProducto().equals(castOther.getCodProducto())))
				&& ((this.getPrecioUnidad() == castOther.getPrecioUnidad())
						|| (this.getPrecioUnidad() != null && castOther.getPrecioUnidad() != null
								&& this.getPrecioUnidad().equals(castOther.getPrecioUnidad())))
				&& ((this.getCantidad() == castOther.getCantidad()) || (this.getCantidad() != null
						&& castOther.getCantidad() != null && this.getCantidad().equals(castOther.getCantidad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNumPresupuesto() == null ? 0 : this.getNumPresupuesto().hashCode());
		result = 37 * result + (getCodProducto() == null ? 0 : this.getCodProducto().hashCode());
		result = 37 * result + (getPrecioUnidad() == null ? 0 : this.getPrecioUnidad().hashCode());
		result = 37 * result + (getCantidad() == null ? 0 : this.getCantidad().hashCode());
		return result;
	}

}
