package Primero;
// Generated 18 ene. 2021 9:58:01 by Hibernate Tools 5.4.21.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Presupuestos generated by hbm2java
 */
public class Presupuestos implements java.io.Serializable {

	private int numPresupuesto;
	private Clientes clientes;
	private Date fechaPresupuesto;
	private BigDecimal porcentajeDescuento;
	private String comentario;
	private Set detallepresupuestoses = new HashSet(0);

	public Presupuestos() {
	}

	public Presupuestos(int numPresupuesto, Date fechaPresupuesto) {
		this.numPresupuesto = numPresupuesto;
		this.fechaPresupuesto = fechaPresupuesto;
	}

	public Presupuestos(int numPresupuesto, Clientes clientes, Date fechaPresupuesto, BigDecimal porcentajeDescuento,
			String comentario, Set detallepresupuestoses) {
		this.numPresupuesto = numPresupuesto;
		this.clientes = clientes;
		this.fechaPresupuesto = fechaPresupuesto;
		this.porcentajeDescuento = porcentajeDescuento;
		this.comentario = comentario;
		this.detallepresupuestoses = detallepresupuestoses;
	}

	public int getNumPresupuesto() {
		return this.numPresupuesto;
	}

	public void setNumPresupuesto(int numPresupuesto) {
		this.numPresupuesto = numPresupuesto;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Date getFechaPresupuesto() {
		return this.fechaPresupuesto;
	}

	public void setFechaPresupuesto(Date fechaPresupuesto) {
		this.fechaPresupuesto = fechaPresupuesto;
	}

	public BigDecimal getPorcentajeDescuento() {
		return this.porcentajeDescuento;
	}

	public void setPorcentajeDescuento(BigDecimal porcentajeDescuento) {
		this.porcentajeDescuento = porcentajeDescuento;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Set getDetallepresupuestoses() {
		return this.detallepresupuestoses;
	}

	public void setDetallepresupuestoses(Set detallepresupuestoses) {
		this.detallepresupuestoses = detallepresupuestoses;
	}

}
