package Primero;
// Generated 18 ene. 2021 9:58:01 by Hibernate Tools 5.4.21.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private int codProducto;
	private String descripcion;
	private BigDecimal precio;
	private BigDecimal stock;
	private Set detallepresupuestoses = new HashSet(0);

	public Productos() {
	}

	public Productos(int codProducto) {
		this.codProducto = codProducto;
	}

	public Productos(int codProducto, String descripcion, BigDecimal precio, BigDecimal stock,
			Set detallepresupuestoses) {
		this.codProducto = codProducto;
		this.descripcion = descripcion;
		this.precio = precio;
		this.stock = stock;
		this.detallepresupuestoses = detallepresupuestoses;
	}

	public int getCodProducto() {
		return this.codProducto;
	}

	public void setCodProducto(int codProducto) {
		this.codProducto = codProducto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getStock() {
		return this.stock;
	}

	public void setStock(BigDecimal stock) {
		this.stock = stock;
	}

	public Set getDetallepresupuestoses() {
		return this.detallepresupuestoses;
	}

	public void setDetallepresupuestoses(Set detallepresupuestoses) {
		this.detallepresupuestoses = detallepresupuestoses;
	}

}
